# general settings
name: WALC_IR_X4
model_type: ESRModel
scale: 4
num_gpu: 4
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: IR700
    type: PairedImageDataset
    dataroot_gt: /home/vision/hongwaiir/datasets/trainsets/IR700_train
    dataroot_lq: /home/vision/hongwaiir/datasets/trainsets/x4
    filename_tmpl: '{}_x4' 
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true

  val_1:
    name: ir7005
    type: PairedImageDataset
    dataroot_gt: /home/vision/hongwaiir/datasets/testsets/ir7005
    dataroot_lq: /home/vision/hongwaiir/datasets/testsets/ir7005d/x4
    filename_tmpl: '{}_x4'     
    io_backend:
      type: disk

  val_2:
    name: ir70015
    type: PairedImageDataset
    dataroot_gt: /home/vision/hongwaiir/datasets/testsets/ir70015
    dataroot_lq: /home/vision/hongwaiir/datasets/testsets/ir70015d/x4
    filename_tmpl: '{}_x4'    
    io_backend:
      type: disk

  val_3:
    name: ir70020
    type: PairedImageDataset
    dataroot_gt: /home/vision/hongwaiir/datasets/testsets/ir70020
    dataroot_lq: /home/vision/hongwaiir/datasets/testsets/ir70020d/x4
    filename_tmpl: '{}_x4'     
    io_backend:
      type: disk
  
  val_4:
    name: Flir
    type: PairedImageDataset
    dataroot_gt: /home/vision/hongwaiir/datasets/testsets/Flir
    dataroot_lq: /home/vision/hongwaiir/datasets/testsets/fld/x4
    filename_tmpl: '{}_x4'     
    io_backend:
      type: disk

  val_5:
    name: IR100
    type: PairedImageDataset
    dataroot_gt: /home/vision/hongwaiir/datasets/testsets/IR100
    dataroot_lq: /home/vision/hongwaiir/datasets/testsets/ir100d/x4
    filename_tmpl: '{}_x4'    
    io_backend:
      type: disk


  val_6:
    name: reC
    type: PairedImageDataset
    dataroot_gt: /home/vision/hongwaiir/datasets/results-C/HR
    dataroot_lq: /home/vision/hongwaiir/datasets/results-C/LR_bicubic/X4
    filename_tmpl: '{}x4'     
    io_backend:
      type: disk     
# network structures
network_g:
  type: WALC
  dim: 64
  pdim: 32
  kernel_size: 13
  n_blocks: 5
  conv_blocks: 5
  window_size: 32
  num_heads: 4
  upscaling_factor: 4
  exp_ratio: 1.25

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: AdamW
    lr: !!float 3e-4
    weight_decay: 0
    betas: [0.9, 0.9]

  scheduler:
    type: MultiStepLR
    milestones: [70000, 140000, 280000, 475000]
    gamma: 0.5

  total_iter: 800000
  warmup_iter: -1  # no warm up

  # losses
#  wave_opt:
#    type: ComplexWaveletLoss
#    loss_weight: 0.5  # 作为辅助损失
#    J: 3
#    magnitude_weight: 1.0
#    phase_weight: 0.05  # 红外图像建议更小的相位权重
#    lowfreq_weight: 0.1
#    criterion: charbonnier
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
# validation settings
val:
  val_freq: !!float 1e3
  save_img: False

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: True
    
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 4
      test_y_channel: True

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: True
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29529
